version: '3'

volumes:
  kudos_db_data:
    driver: local

services:
  kudos-db:
    image: postgres:12-alpine
    container_name: kudos-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - kudos_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kudos_database
      - POSTGRES_PASSWORD=kudos
    networks:
      - challenge-network

networks:
  challenge-network:
    driver: bridge
